"""Deterministic no-provider stub LLM.

This is the built-in default LLM provider.  It exists so the
``llm_expanded`` compiler mode can exercise its citation-validation and
content-hash plumbing in tests and in environments where the ``llm`` extra
is intentionally absent — without ever performing an external LLM call.

Design decisions
----------------
* **Fully deterministic** — section content is derived from
  ``(node_id, request.topic)`` via plain f-strings; no time-based seeds, no
  UUID, no ``os.urandom``, no random sampling.  Two calls with the same
  inputs produce byte-identical output.
* **Source-locked by construction** — every emitted GeneratedSection cites
  exactly one node id, that id being one of the active node ids supplied by
  the caller.  The stub NEVER fabricates a citation that the caller did not
  provide; the mode's citation validator is therefore effectively a no-op
  for stub output (but it still runs as a safety net).
* **One section per active node** — for a packet of N nodes the stub
  produces exactly N GeneratedSections, in node-id-sorted order.  This
  keeps the number of sections proportional to packet size so determinism
  tests can fail cheaply when something drifts.
* **No I/O, no imports of optional packages** — the stub does not import
  ``openai``, ``anthropic``, ``nbformat``, ``jinja2``, or any other
  optional package.  It is always-on and never requires the ``llm`` extra.
"""

from __future__ import annotations

from akms_learn.models.llm_expansion import (
    GeneratedSection,
    LLMExpansionPolicy,
    compute_content_hash,
)

__all__ = [
    "NO_PROVIDER_STUB_GENERATOR",
    "NO_PROVIDER_STUB_MODEL",
    "no_provider_stub",
]


#: Generator id surfaced on every GeneratedSection the stub emits.  Tests rely
#: on this exact string to distinguish stub output from real-provider output.
NO_PROVIDER_STUB_GENERATOR: str = "no_provider_stub"

#: Model id surfaced on every GeneratedSection the stub emits.  Distinct from
#: the generator so downstream consumers can disambiguate provider vs. model.
NO_PROVIDER_STUB_MODEL: str = "deterministic-stub-v1"


def _build_section_content(node_id: str, topic: str) -> str:
    """Return deterministic explanatory prose for one node.

    The text is composed from ``(node_id, topic)`` via a fixed f-string so
    the resulting bytes are byte-stable across runs, machines, and Python
    versions.  No timestamps, no random tokens, no per-call entropy.
    """
    return (
        f"Explanatory paragraph for node {node_id!r} in the context of "
        f"topic {topic!r}.  This text is generated by the built-in "
        "no-provider stub and paraphrases the source node without "
        "introducing new claims."
    )


def no_provider_stub(
    topic: str,
    active_node_ids: tuple[str, ...] | list[str],
    policy: LLMExpansionPolicy | None = None,
    *,
    sources: object | None = None,
) -> list[GeneratedSection]:
    """Return a deterministic canned list of :class:`GeneratedSection`s.

    Parameters
    ----------
    topic:
        Free-form topic string from the request.  Embedded verbatim into
        the generated content so two runs with the same topic produce the
        same content bytes (and therefore the same content hash).
    active_node_ids:
        The node ids that appear in the deterministic packet.  The stub
        emits exactly one explanatory section per id, in sorted order.

    Returns
    -------
    list[GeneratedSection]
        Sections in node-id-sorted order.  The list is freshly constructed
        on every call so callers may mutate it without affecting future
        invocations.  Every entry has ``validation_status="valid"`` and a
        ``content_hash`` computed via
        :func:`~akms_learn.models.llm_expansion.compute_content_hash`.
    """
    # Sort + dedup defensively: callers should already pass sorted unique
    # ids, but the stub must never depend on caller discipline for the
    # determinism contract.
    sorted_ids: list[str] = sorted({str(nid) for nid in active_node_ids if nid})

    sections: list[GeneratedSection] = []
    for nid in sorted_ids:
        content = _build_section_content(nid, topic)
        section_id = f"{nid}::explanation"
        section_source_ids: tuple[str, ...] = (nid,)
        content_hash = compute_content_hash(
            section_id=section_id,
            source_node_ids=section_source_ids,
            content=content,
        )
        sections.append(
            GeneratedSection(
                id=section_id,
                generator=NO_PROVIDER_STUB_GENERATOR,
                model=NO_PROVIDER_STUB_MODEL,
                source_node_ids=section_source_ids,
                validation_status="valid",
                content_hash=content_hash,
                content=content,
            )
        )
    return sections
